#! /bin/bash

####
# Written by Sriranga Kashyap <kashyap.sriranga@gmail.com>
# Maastricht, 2020-06
####

export AFNI_NIFTI_TYPE_WARN=NO
export AFNI_ENVIRON_WARNINGS=NO

# Simple formatting
bold=$(tput bold)
normal=$(tput sgr0)

# Help
function Help() {
    cat <<HELP

Usage:

$(basename $0) ${bold}-i${normal} INV2 image ${bold}-u${normal} UNI image ${bold}-r${normal} re-bias

--------------------------------------------------------------------------------
Input arguments:

    -i: MP2RAGE INV2 magnitude image ( e.g. /path/to/source/inv2_mag.nii.gz )

    -u: MP2RAGE UNI image ( e.g. /path/to/source/uni.nii.gz )

    -r: Reintroduce bias-field ( default = 0 . optional)

--------------------------------------------------------------------------------

Example:

$(basename $0) -i /data/inv2.nii.gz -u /data/uni.nii.gz

--------------------------------------------------------------------------------
Script was created by: Sriranga Kashyap (06-2020), kashyap.sriranga@gmail.com
--------------------------------------------------------------------------------

HELP
    exit 1
}

# Check for flag
if [[ "$1" == "-h" || $# -eq 0 ]]; then
    Help >&2
fi

# Get some info
Aversion=$(afni -ver)
runDate=$(echo $(date))


# Parse input arguments
while getopts "h:i:r:u:" OPT; do
    case $OPT in
        h) #help
            Help
            exit 0
        ;;
        i) # INV2 image
            inv2_image=$OPTARG
        ;;
        r) # Rebias boolean
            re_bias=$OPTARG
        ;;
        u) # UNI image
            uni_image=$OPTARG
        ;;
        \?) # report error
            echo "$HELP" >&2
            exit 1
        ;;
    esac
done


if [ ! -z "$re_bias" ]; then
    echo ""
    echo "++ UNI will ${bold} NOT ${normal} be bias-corrected."
    echo ""
    re_bias=1
    
else
    echo ""
    echo "++ UNI will be bias-corrected."
    echo ""
    re_bias=0
    
fi

# Check extension
if [ ${inv2_image##*.} = gz ]; then
    inv2_basename=$(basename $inv2_image .nii.gz)
    uni_basename=$(basename $uni_image .nii.gz)
else
    inv2_basename=$(basename $inv2_image .nii)
    uni_basename=$(basename $uni_image .nii)
fi

# Check if bias field should be removed or not
if [ "$re_bias" = 0 ]; then
    echo ""
    echo "++ Removing bias-field."
    echo ""
    # Unifize INV2
    3dUnifize \
    -quiet \
    -overwrite \
    -prefix ${inv2_basename}_bfc.nii \
    $inv2_image

    out_name=${uni_basename}_unbiased_clean.nii
    
else
    echo ""
    echo "++ Reintroducing bias-field."
    echo ""
    3dcopy $inv2_image ${inv2_basename}_bfc.nii

    out_name=${uni_basename}_rebiased_clean.nii
    
fi

# Intensity Normalise INV2 between 0-1
int_max=$(3dinfo -dmaxus $inv2_image)
int_min=$(3dinfo -dminus $inv2_image)

3dcalc \
-overwrite \
-a ${inv2_basename}_bfc.nii \
-expr "( a - $int_min ) / ( $int_max - $int_min )" \
-prefix ${inv2_basename}_intnorm.nii
echo ""
echo "++ MPRAGEising the UNI image."
echo ""
# Multiply intensity normalised INV2 to UNI image
3dcalc \
-overwrite \
-a $uni_image \
-b ${inv2_basename}_intnorm.nii \
-expr "a * b" \
-prefix $out_name

# Remove intermediate files
rm ${inv2_basename}_bfc.nii ${inv2_basename}_intnorm.nii
echo ""
echo "++ Done."
echo ""
